### ISSUE TITLE
No longer works as of HA 2024.3

### ISSUE THREAD

**Issue by ShonP40** [hristo-atanasov/Tasmota-IRHVAC#134]
Getting this in the log:

```
ERROR (MainThread) [homeassistant.components.climate] Error adding entity climate.a_c for domain climate with platform tasmota_irhvac
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 865, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1327, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/tasmota_irhvac/climate.py", line 544, in async_added_to_hass
    await super().async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 587, in async_added_to_hass
    self._availability_prepare_subscribe_topics()
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 638, in _availability_prepare_subscribe_topics
    @log_messages(self.hass, self.entity_id)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 28, in log_messages
    debug_info_entities = get_mqtt_data(hass).debug_info_entities
                          ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mqtt/util.py", line 179, in get_mqtt_data
    mqtt_data = hass.data[DATA_MQTT]
                ~~~~~~~~~^^^^^^^^^^^
KeyError: 'mqtt'
```

Could be related to some of the changes done here: https://github.com/home-assistant/core/pull/109513

**Comment by ShonP40** [comment]
nvm, a restart fixed it
weird
