### ISSUE TITLE
Hassio update 2024.04.0

### ISSUE THREAD

**Issue by riddik14** [hristo-atanasov/Tasmota-IRHVAC#135]
Registratore: homeassistant.components.climate
Fonte: helpers/entity_platform.py:580
Integrazione: Climatizzatore (documentazione, problemi)
Prima occorrenza: 22:38:31 (1 occorrenze)
Ultima registrazione: 22:38:31

Error adding entity climate.raffreddamento for domain climate with platform tasmota_irhvac
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 881, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1333, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/tasmota_irhvac/climate.py", line 552, in async_added_to_hass
    await super().async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 588, in async_added_to_hass
    self._availability_prepare_subscribe_topics()
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 639, in _availability_prepare_subscribe_topics
    @log_messages(self.hass, self.entity_id)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 29, in log_messages
    debug_info_entities = get_mqtt_data(hass).debug_info_entities
                          ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mqtt/util.py", line 222, in get_mqtt_data
    mqtt_data = hass.data[DATA_MQTT]
                ~~~~~~~~~^^^^^^^^^^^
KeyError: 'mqtt'

**Comment by riddik14** [comment]
- platform: tasmota_irhvac
    name: "Raffreddamento"
    command_topic: "ac-panasonic/cmnd/irhvac"
    state_topic: "ac-panasonic/stat/RESULT"
    availability_topic: "ac-panasonic/tele/LWT"
    temperature_sensor: sensor.temperatura_media_interna
    humidity_sensor: sensor.umidita_media_interna 
    vendor: "PANASONIC_AC"
    min_temp: 16 #optional - default 16 int value
    max_temp: 32 #optional - default 32 int value
    target_temp: 23 #optional - default 26 int value
    initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
    away_temp: 22 #optional - default 24 int value
    precision: 1 #optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
    supported_modes:
      - "heat"
      - "cool"
      - "dry"
      - "auto"
      - "off" #Turns the AC off - Should be in quotes
    supported_fan_speeds:
      - "low"
      - "medium"
      - "high"
      - "min"
      - "auto"
    supported_swing_list:
      - "off"
      - "vertical"
    #hvac_model: "-1" #optional - default "1" string value
    celsius_mode: "On" #optional - default "On" string value
    #toggle_list: #optional - default []
      #-
