### ISSUE TITLE
HomeAssistent 2024.11 Error - Not usable

### ISSUE THREAD

**Issue by duczz** [hristo-atanasov/Tasmota-IRHVAC#162]
Logger: homeassistant.config
Quelle: config.py:1053
Erstmals aufgetreten: 13:14:52 (3 Vorkommnisse)
Zuletzt protokolliert: 13:14:52

Platform error: climate - No module named 'homeassistant.components.mqtt.mixins'
Traceback (most recent call last):
  File "/config/custom_components/tasmota_irhvac/climate.py", line 13, in <module>
    from homeassistant.components.mqtt.schemas import MQTT_AVAILABILITY_SCHEMA
ImportError: cannot import name 'MQTT_AVAILABILITY_SCHEMA' from 'homeassistant.components.mqtt.schemas' (/usr/src/homeassistant/homeassistant/components/mqtt/schemas.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1053, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1104, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1199, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'homeassistant.components.mqtt.mixins'

**Comment by duczz** [comment]
Ah 2 hours ago a Update was released for that
