### ISSUE TITLE
AttributeError: module 'homeassistant.components.mqtt' has no attribute 'subscription'

### ISSUE THREAD

**Issue by Qweritos** [hristo-atanasov/Tasmota-IRHVAC#36]
Logger: homeassistant.components.climate
Source: custom_components/tasmota_irhvac/climate.py:643
Integration: Climate (documentation, issues)
First occurred: 11:45:03 PM (2 occurrences)
Last logged: 11:45:03 PM
```
Error adding entities for domain climate with platform tasmota_irhvac
Error while setting up tasmota_irhvac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 529, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/tasmota_irhvac/climate.py", line 500, in async_added_to_hass
    await self._subscribe_topics()
  File "/config/custom_components/tasmota_irhvac/climate.py", line 643, in _subscribe_topics
    self._sub_state = await mqtt.subscription.async_subscribe_topics(
AttributeError: module 'homeassistant.components.mqtt' has no attribute 'subscription'
```

```
Version | core-2021.3.4
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.10.22-0-lts
CPU Architecture | x86_64
Timezone | Europe/Moscow
```

**Comment by hristo-atanasov** [comment]
This custom integration needs mqtt component. I guess you are not using home assistant operating system, but just the core, right?

**Comment by huynguyendt1** [comment]
> Tích hợp tùy chỉnh này cần thành phần mqtt. Tôi đoán bạn đang không sử dụng hệ điều hành trợ lý gia đình, mà chỉ là phần lõi, phải không?

hello Sir!!! Can you help me?

Logger: homeassistant.components.climate
Source: custom_components/tasmota_irhvac/climate.py:643
Integration: Climate (documentation, issues)
First occurred: 5:03:08 PM (2 occurrences)
Last logged: 5:03:08 PM

Error adding entities for domain climate with platform tasmota_irhvac
Error while setting up tasmota_irhvac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 614, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/tasmota_irhvac/climate.py", line 500, in async_added_to_hass
    await self._subscribe_topics()
  File "/config/custom_components/tasmota_irhvac/climate.py", line 643, in _subscribe_topics
    self._sub_state = await mqtt.subscription.async_subscribe_topics(
AttributeError: module 'homeassistant.components.mqtt' has no attribute 'subscription'

 Version
core-2021.6.2

**Comment by cr4zyc4t** [comment]
I face exactly this error when trying to setup remote for my Gree AC. And I'm sure that my HassIO already integrated with MQTT, I could use HassIO UI to subscribe to events from tasmota ir normally.
Might be some API of MQTT changed?

**Comment by cr4zyc4t** [comment]
RESOLVED!!!
Just install  Tasmota Integration and make sure your IR blaster can be discovered!

**Comment by hristo-atanasov** [comment]
Do you still have the issue/problem?

**Comment by hristo-atanasov** [comment]
OK, closing the issue as workaround was presented.
