### ISSUE TITLE
Tasmota IRHVAC for HA v2021.12.1+ v2021.12.21 Not working adding climate components.

### ISSUE THREAD

**Issue by xinux87** [hristo-atanasov/Tasmota-IRHVAC#60]
Hi I'm getting this errro after update, HOme assistant and To the last IRHVAC version.

It was working fine...

Thanks!!!

Logger: homeassistant.components.climate
Source: custom_components/tasmota_irhvac/climate.py:998
Integration: Climate (documentation, issues)
First occurred: 12:49:11 PM (2 occurrences)
Last logged: 12:49:11 PM

Error adding entities for domain climate with platform tasmota_irhvac
Error while setting up tasmota_irhvac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/tasmota_irhvac/climate.py", line 525, in async_added_to_hass
    self._async_update_temp(temp_sensor_state.state)
  File "/config/custom_components/tasmota_irhvac/climate.py", line 998, in _async_update_temp
    self._cur_temp = float(state.state)
AttributeError: 'str' object has no attribute 'state'

**Comment by leranp** [comment]
Some here

**Comment by nao-pon** [comment]
@xinux87 , @leranp Please modify line 525 of climate.py as follows and let us know the result.

FROM:
`self._async_update_temp(temp_sensor_state.state)`
TO:
`self._async_update_temp(temp_sensor_state)`

**Comment by leranp** [comment]
> @xinux87 , @leranp Please modify line 525 of climate.py as follows and let us know the result.
> 
> FROM: `self._async_update_temp(temp_sensor_state.state)` TO: `self._async_update_temp(temp_sensor_state)`

its fixed. Thanks

**Comment by xinux87** [comment]
It works!!
thank you, so much sorry for the delay, !!
