### ISSUE TITLE
Homekit will not create hvac entity in homekit component in startup if state is auto

### ISSUE THREAD

**Issue by chicaneau** [hristo-atanasov/Tasmota-IRHVAC#62]
Please see [https://github.com/home-assistant/core/issues/66784](url)

homekit component dev advised there is an issue with sending 'auto' as a hvac action as this is not a supported action by the core HVAC component, see here [https://developers.home-assistant.io/docs/core/entity/climate/?_highlight=hvac#hvac-action](url)

**Comment by ahmetem** [comment]
Logger: homeassistant.components.homekit
Source: components/homekit/type_thermostats.py:624
Integration: HomeKit ([documentation](https://www.home-assistant.io/integrations/homekit), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+homekit%22))
First occurred: 00:05:19 (1 occurrences)
Last logged: 00:05:19

Failed to create a HomeKit accessory for climate.klima
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 595, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 222, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 357, in __init__
    self._async_update_state(state)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 624, in _async_update_state
    homekit_hvac_action = HC_HASS_TO_HOMEKIT_ACTION[hvac_action]
KeyError: 'unavailable'

**Comment by hristo-atanasov** [comment]
This integration is written for Home Assistant. We support Home Assistant. We support "auto" and "unavailable". HomeKit integration does not fully support all Home Assistant "modes" and "statuses". Also HomeKit integration cannot support everything, that most of the Air Conditioners support. It is following some Apple's rules and we know that Apple are not "the same", they are "different". It is not working because Apple don't think people need this modes. But people do. Home Assistant do. So don't get me wrong, I'm Apple Swift developer (my daily job), but ask HomeKit developers to support us. Don't ask us to break 50% of the functionality and compatibility of this integration, just to conform some Apple or HomeKit rules. If someone, for some reason, find this answer for "rude", I can just suggest him to buy Smart AC with built-in HomeKit support! Or use HomeKit for the supported things and Home Assistant for everything else. This integration is for all other people that have regular not so smart ACs and don't mind to use Home Assistant UI and/or Android device as a way to control their smart home. :) If HomeKit integration devs think that I can help them somehow - I'm open for ideas. But in this case they have to contact us, not you - their end user.  I'm leaving this issue open, just in case someone want to add something meaningful. :)

**Comment by hristo-atanasov** [comment]
@chicaneau @ahmetem 
Can you replace your current `climate.py` with the linked one from below (open the link -> right click on the page -> save file)? Home Assistant restart is needed after replacing the file. Check if everything in HomeKit works now and keep me updated with the results. Thank you in advance!
[https://raw.githubusercontent.com/hristo-atanasov/Tasmota-IRHVAC/webkit-fix/custom_components/tasmota_irhvac/climate.py](https://raw.githubusercontent.com/hristo-atanasov/Tasmota-IRHVAC/webkit-fix/custom_components/tasmota_irhvac/climate.py)

**Comment by hristo-atanasov** [comment]
Ok, update to the latest v2022.04.08 and update me with the results. :)

**Comment by chicaneau** [comment]
@hristo-atanasov nice work!! you solved it! v2022.04.08 appears to be working perfectly on restart, persistence is remaining! thankyou so much
