### ISSUE TITLE
Home Assistant 2022.6.1 - MQTT no attribute 'MQTT_BASE_PLATFORM_SCHEMA'

### ISSUE THREAD

**Issue by Kryoh-hash** [hristo-atanasov/Tasmota-IRHVAC#74]
Hi,

Since the latest update and the mqtt mess around with the new scheme, im getting this errors, and it doesnt load on my dashboard, i guess that some changes has to be made with the mqtt part in the component.

```
Logger: homeassistant.config
Source: loader.py:627
First occurred: 09:31:14 (3 occurrences)
Last logged: 09:31:14

Platform error: climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/tasmota_irhvac/climate.py", line 271, in <module>
    PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend(mqtt.MQTT_BASE_PLATFORM_SCHEMA.schema)
AttributeError: module 'homeassistant.components.mqtt' has no attribute 'MQTT_BASE_PLATFORM_SCHEMA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 627, in get_platform
    raise ImportError(
ImportError: Exception importing custom_components.tasmota_irhvac.climate
```

```
Logger: homeassistant.loader
Source: custom_components/tasmota_irhvac/climate.py:271
Integration: tasmota_irhvac (documentation, issues)
First occurred: 09:31:14 (3 occurrences)
Last logged: 09:31:14

Unexpected exception importing platform custom_components.tasmota_irhvac.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/tasmota_irhvac/climate.py", line 271, in <module>
    PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend(mqtt.MQTT_BASE_PLATFORM_SCHEMA.schema)
AttributeError: module 'homeassistant.components.mqtt' has no attribute 'MQTT_BASE_PLATFORM_SCHEMA'

```

**Comment by arevaclier** [comment]
I pushed a small fix as I was encountering the same issue (#75)

**Comment by Kryoh-hash** [comment]
> I pushed a small fix as I was encountering the same issue (#75)

Fixed !

Thanks !
